#!/usr/bin/env python3
"""Canonical TM catalogues offered by the randomizer.

Each profile uses one representative main-series game's official TM order.
The data is embedded so frozen builds do not depend on developer-only tools.
"""

_RAW_CATALOGS = {
    "gen1": ("Generation I", "Pokémon Yellow",
        "MEGA_PUNCH RAZOR_WIND SWORDS_DANCE WHIRLWIND MEGA_KICK TOXIC HORN_DRILL BODY_SLAM TAKE_DOWN DOUBLE_EDGE "
        "BUBBLE_BEAM WATER_GUN ICE_BEAM BLIZZARD HYPER_BEAM PAY_DAY SUBMISSION COUNTER SEISMIC_TOSS RAGE "
        "MEGA_DRAIN SOLAR_BEAM DRAGON_RAGE THUNDERBOLT THUNDER EARTHQUAKE FISSURE DIG PSYCHIC TELEPORT "
        "MIMIC DOUBLE_TEAM REFLECT BIDE METRONOME SELF_DESTRUCT EGG_BOMB FIRE_BLAST SWIFT SKULL_BASH "
        "SOFT_BOILED DREAM_EATER SKY_ATTACK REST THUNDER_WAVE PSYWAVE EXPLOSION ROCK_SLIDE TRI_ATTACK SUBSTITUTE"
    ),
    "gen2": ("Generation II", "Pokémon Crystal",
        "DYNAMIC_PUNCH HEADBUTT CURSE ROLLOUT ROAR TOXIC ZAP_CANNON ROCK_SMASH PSYCH_UP HIDDEN_POWER "
        "SUNNY_DAY SWEET_SCENT SNORE BLIZZARD HYPER_BEAM ICY_WIND PROTECT RAIN_DANCE GIGA_DRAIN ENDURE "
        "FRUSTRATION SOLAR_BEAM IRON_TAIL DRAGON_BREATH THUNDER EARTHQUAKE RETURN DIG PSYCHIC SHADOW_BALL "
        "MUD_SLAP DOUBLE_TEAM ICE_PUNCH SWAGGER SLEEP_TALK SLUDGE_BOMB SANDSTORM FIRE_BLAST SWIFT DEFENSE_CURL "
        "THUNDER_PUNCH DREAM_EATER DETECT REST ATTRACT THIEF STEEL_WING FIRE_PUNCH FURY_CUTTER NIGHTMARE"
    ),
    "gen3": ("Generation III", "Pokémon Emerald",
        "FOCUS_PUNCH DRAGON_CLAW WATER_PULSE CALM_MIND ROAR TOXIC HAIL BULK_UP BULLET_SEED HIDDEN_POWER "
        "SUNNY_DAY TAUNT ICE_BEAM BLIZZARD HYPER_BEAM LIGHT_SCREEN PROTECT RAIN_DANCE GIGA_DRAIN SAFEGUARD "
        "FRUSTRATION SOLAR_BEAM IRON_TAIL THUNDERBOLT THUNDER EARTHQUAKE RETURN DIG PSYCHIC SHADOW_BALL "
        "BRICK_BREAK DOUBLE_TEAM REFLECT SHOCK_WAVE FLAMETHROWER SLUDGE_BOMB SANDSTORM FIRE_BLAST ROCK_TOMB AERIAL_ACE "
        "TORMENT FACADE SECRET_POWER REST ATTRACT THIEF STEEL_WING SKILL_SWAP SNATCH OVERHEAT"
    ),
    "gen4": ("Generation IV", "Pokémon Platinum",
        "FOCUS_PUNCH DRAGON_CLAW WATER_PULSE CALM_MIND ROAR TOXIC HAIL BULK_UP BULLET_SEED HIDDEN_POWER "
        "SUNNY_DAY TAUNT ICE_BEAM BLIZZARD HYPER_BEAM LIGHT_SCREEN PROTECT RAIN_DANCE GIGA_DRAIN SAFEGUARD "
        "FRUSTRATION SOLAR_BEAM IRON_TAIL THUNDERBOLT THUNDER EARTHQUAKE RETURN DIG PSYCHIC SHADOW_BALL "
        "BRICK_BREAK DOUBLE_TEAM REFLECT SHOCK_WAVE FLAMETHROWER SLUDGE_BOMB SANDSTORM FIRE_BLAST ROCK_TOMB AERIAL_ACE "
        "TORMENT FACADE SECRET_POWER REST ATTRACT THIEF STEEL_WING SKILL_SWAP SNATCH OVERHEAT "
        "ROOST FOCUS_BLAST ENERGY_BALL FALSE_SWIPE BRINE FLING CHARGE_BEAM ENDURE DRAGON_PULSE DRAIN_PUNCH "
        "WILL_O_WISP SILVER_WIND EMBARGO EXPLOSION SHADOW_CLAW PAYBACK RECYCLE GIGA_IMPACT ROCK_POLISH FLASH "
        "STONE_EDGE AVALANCHE THUNDER_WAVE GYRO_BALL SWORDS_DANCE STEALTH_ROCK PSYCH_UP CAPTIVATE DARK_PULSE ROCK_SLIDE "
        "X_SCISSOR SLEEP_TALK NATURAL_GIFT POISON_JAB DREAM_EATER GRASS_KNOT SWAGGER PLUCK U_TURN SUBSTITUTE "
        "FLASH_CANNON TRICK_ROOM"
    ),
    "gen5": ("Generation V", "Pokémon Black 2 / White 2",
        "HONE_CLAWS DRAGON_CLAW PSYSHOCK CALM_MIND ROAR TOXIC HAIL BULK_UP VENOSHOCK HIDDEN_POWER "
        "SUNNY_DAY TAUNT ICE_BEAM BLIZZARD HYPER_BEAM LIGHT_SCREEN PROTECT RAIN_DANCE TELEKINESIS SAFEGUARD "
        "FRUSTRATION SOLAR_BEAM SMACK_DOWN THUNDERBOLT THUNDER EARTHQUAKE RETURN DIG PSYCHIC SHADOW_BALL "
        "BRICK_BREAK DOUBLE_TEAM REFLECT SLUDGE_WAVE FLAMETHROWER SLUDGE_BOMB SANDSTORM FIRE_BLAST ROCK_TOMB AERIAL_ACE "
        "TORMENT FACADE FLAME_CHARGE REST ATTRACT THIEF LOW_SWEEP ROUND ECHOED_VOICE OVERHEAT "
        "ALLY_SWITCH FOCUS_BLAST ENERGY_BALL FALSE_SWIPE SCALD FLING CHARGE_BEAM SKY_DROP INCINERATE QUASH "
        "WILL_O_WISP ACROBATICS EMBARGO EXPLOSION SHADOW_CLAW PAYBACK RETALIATE GIGA_IMPACT ROCK_POLISH FLASH "
        "STONE_EDGE VOLT_SWITCH THUNDER_WAVE GYRO_BALL SWORDS_DANCE STRUGGLE_BUG PSYCH_UP BULLDOZE FROST_BREATH ROCK_SLIDE "
        "X_SCISSOR DRAGON_TAIL WORK_UP POISON_JAB DREAM_EATER GRASS_KNOT SWAGGER PLUCK U_TURN SUBSTITUTE "
        "FLASH_CANNON TRICK_ROOM WILD_CHARGE ROCK_SMASH SNARL"
    ),
    "gen6": ("Generation VI", "Pokémon Omega Ruby / Alpha Sapphire",
        "HONE_CLAWS DRAGON_CLAW PSYSHOCK CALM_MIND ROAR TOXIC HAIL BULK_UP VENOSHOCK HIDDEN_POWER "
        "SUNNY_DAY TAUNT ICE_BEAM BLIZZARD HYPER_BEAM LIGHT_SCREEN PROTECT RAIN_DANCE ROOST SAFEGUARD "
        "FRUSTRATION SOLAR_BEAM SMACK_DOWN THUNDERBOLT THUNDER EARTHQUAKE RETURN DIG PSYCHIC SHADOW_BALL "
        "BRICK_BREAK DOUBLE_TEAM REFLECT SLUDGE_WAVE FLAMETHROWER SLUDGE_BOMB SANDSTORM FIRE_BLAST ROCK_TOMB AERIAL_ACE "
        "TORMENT FACADE FLAME_CHARGE REST ATTRACT THIEF LOW_SWEEP ROUND ECHOED_VOICE OVERHEAT "
        "STEEL_WING FOCUS_BLAST ENERGY_BALL FALSE_SWIPE SCALD FLING CHARGE_BEAM SKY_DROP INCINERATE QUASH "
        "WILL_O_WISP ACROBATICS EMBARGO EXPLOSION SHADOW_CLAW PAYBACK RETALIATE GIGA_IMPACT ROCK_POLISH FLASH "
        "STONE_EDGE VOLT_SWITCH THUNDER_WAVE GYRO_BALL SWORDS_DANCE STRUGGLE_BUG PSYCH_UP BULLDOZE FROST_BREATH ROCK_SLIDE "
        "X_SCISSOR DRAGON_TAIL INFESTATION POISON_JAB DREAM_EATER GRASS_KNOT SWAGGER SLEEP_TALK U_TURN SUBSTITUTE "
        "FLASH_CANNON TRICK_ROOM WILD_CHARGE SECRET_POWER SNARL NATURE_POWER DARK_PULSE POWER_UP_PUNCH DAZZLING_GLEAM CONFIDE"
    ),
    "gen7": ("Generation VII", "Pokémon Ultra Sun / Ultra Moon",
        "WORK_UP DRAGON_CLAW PSYSHOCK CALM_MIND ROAR TOXIC HAIL BULK_UP VENOSHOCK HIDDEN_POWER "
        "SUNNY_DAY TAUNT ICE_BEAM BLIZZARD HYPER_BEAM LIGHT_SCREEN PROTECT RAIN_DANCE ROOST SAFEGUARD "
        "FRUSTRATION SOLAR_BEAM SMACK_DOWN THUNDERBOLT THUNDER EARTHQUAKE RETURN LEECH_LIFE PSYCHIC SHADOW_BALL "
        "BRICK_BREAK DOUBLE_TEAM REFLECT SLUDGE_WAVE FLAMETHROWER SLUDGE_BOMB SANDSTORM FIRE_BLAST ROCK_TOMB AERIAL_ACE "
        "TORMENT FACADE FLAME_CHARGE REST ATTRACT THIEF LOW_SWEEP ROUND ECHOED_VOICE OVERHEAT "
        "STEEL_WING FOCUS_BLAST ENERGY_BALL FALSE_SWIPE SCALD FLING CHARGE_BEAM SKY_DROP BRUTAL_SWING QUASH "
        "WILL_O_WISP ACROBATICS EMBARGO EXPLOSION SHADOW_CLAW PAYBACK SMART_STRIKE GIGA_IMPACT ROCK_POLISH AURORA_VEIL "
        "STONE_EDGE VOLT_SWITCH THUNDER_WAVE GYRO_BALL SWORDS_DANCE FLY PSYCH_UP BULLDOZE FROST_BREATH ROCK_SLIDE "
        "X_SCISSOR DRAGON_TAIL INFESTATION POISON_JAB DREAM_EATER GRASS_KNOT SWAGGER SLEEP_TALK U_TURN SUBSTITUTE "
        "FLASH_CANNON TRICK_ROOM WILD_CHARGE SURF SNARL NATURE_POWER DARK_PULSE WATERFALL DAZZLING_GLEAM CONFIDE"
    ),
    "gen8": ("Generation VIII", "Pokémon Brilliant Diamond / Shining Pearl",
        "FOCUS_PUNCH DRAGON_CLAW WATER_PULSE CALM_MIND ROAR TOXIC HAIL BULK_UP BULLET_SEED WORK_UP "
        "SUNNY_DAY TAUNT ICE_BEAM BLIZZARD HYPER_BEAM LIGHT_SCREEN PROTECT RAIN_DANCE GIGA_DRAIN SAFEGUARD "
        "DAZZLING_GLEAM SOLAR_BEAM IRON_TAIL THUNDERBOLT THUNDER EARTHQUAKE LOW_SWEEP DIG PSYCHIC SHADOW_BALL "
        "BRICK_BREAK DOUBLE_TEAM REFLECT SHOCK_WAVE FLAMETHROWER SLUDGE_BOMB SANDSTORM FIRE_BLAST ROCK_TOMB AERIAL_ACE "
        "TORMENT FACADE VOLT_SWITCH REST ATTRACT THIEF STEEL_WING SKILL_SWAP SCALD OVERHEAT "
        "ROOST FOCUS_BLAST ENERGY_BALL FALSE_SWIPE BRINE FLING CHARGE_BEAM ENDURE DRAGON_PULSE DRAIN_PUNCH "
        "WILL_O_WISP BUG_BUZZ NASTY_PLOT EXPLOSION SHADOW_CLAW PAYBACK RECYCLE GIGA_IMPACT ROCK_POLISH FLASH "
        "STONE_EDGE AVALANCHE THUNDER_WAVE GYRO_BALL SWORDS_DANCE STEALTH_ROCK PSYCH_UP SNARL DARK_PULSE ROCK_SLIDE "
        "X_SCISSOR SLEEP_TALK BULLDOZE POISON_JAB DREAM_EATER GRASS_KNOT SWAGGER PLUCK U_TURN SUBSTITUTE "
        "FLASH_CANNON TRICK_ROOM CUT FLY SURF STRENGTH DEFOG ROCK_SMASH WATERFALL ROCK_CLIMB"
    ),
}

TM_CATALOGS = {
    key: {
        "generation": generation,
        "game": game,
        "moves": tuple(moves.split()),
        "label": f"{generation} — {game} ({len(moves.split())} TMs)",
    }
    for key, (generation, game, moves) in _RAW_CATALOGS.items()
}

TM_CATALOG_KEYS = tuple(TM_CATALOGS)
DEFAULT_TM_CATALOG = "gen3"
FIRST_TM_CATALOG = "gen1"


def catalogue_label(key):
    """Return the user-facing label for a catalogue key."""
    return TM_CATALOGS[key]["label"]

# Exact untouched Emerald TM item definitions. Decoded only when restoring Gen III.
ORIGINAL_GEN3_TM_ITEMS_B64 = (
    "eNrtnd9z2zYSx9/7V2DSmWtvxklt2RbJhzzQEm1prF+lqPqSuxsNRIIizhShAqAdtdM/6P6O+8duQVqOcqRT2GWmw+D8kLQhYtH7"
    "5e5+drFgvvkGwdffh4E3Xgbj5eW0t5gvZ4tJb/BP9La49mvxq/p6k+ENQW9RsXjijr3vXwXj45NXfz36uGTLaajWnB4fHx/8cURE"
    "yOlWUpbBxd50PJsuJv3lPPCHk6vvH9epr1czdk94nKdHaJVLtMG3RPwje/XpGpkQlAvCUZzSLEwQjStLEirRaofUypiRN5/cJd1s"
    "GZc4K251uPS9xdy9GHlggfnhz8LCWyJhxWzau/YCZZ/B+OC63G0fzbGYe8uZ6wfvlmNvsjhYFFOSRgtBLvMsVIsl2cD/TXM5jS+w"
    "lCmBb7v/rr8dffOpHH3fvZpOlr2Re6MrR6dpOQaM3QqEswiJFIvkCTHAxOieygSlLFsfVZaIBPMtClN8L9qpxI0beD44xmju6Spx"
    "2rQSVyQjHEui1KhYOE8lx4JlNET3+I7UiISVM+1QyLIYXKedMvTc0Xg5Hk76uiKcNS2Cj6kABebbN8iVt8ovKqZW1/okVtEnZmEu"
    "aLau9ZkNzaJ2yuBPXV9XgfNaBU5eroCLBL7Da4I4wxyp57pi3SJp7EM/5AhCUFUBhggENbVoVfzA7ZQimP5t2NPVott8rqYQcx5N"
    "XTFykRIwkuwDzeqlWnMc5ThNd+iecUGyluaHgTsc6apg/Y4K39IYXSxnvnfp+b7XXw573vLGc4OB56O3b+HSwR8s55PpzR+KZEo6"
    "iFZg+ap8LEZDuLnCfL/OrseT3ypLYsbROZI5P1DuW5IK8rKb6nFSZjiUYJoKyfimPpVFeAMxABamaXUB3K9A5ENItlL9AAc3lkU0"
    "bt/TdbEYXS8XM90HzG7azS/yFBgw35bRkkW7umi6YkwAcjOZVK66UuLwFv1l/6C108dBhRF88NzztPHDaVqJecKYFKgDIRXcThAS"
    "VXkcQi2G5Hiv1gjJ6S15CtlbGmuH/b43Wc6mN54uhZwcNy1EABbE5WO9VQVrxcR3mFMVnzasBv8gCsWEk0yiGbv9z79hTTulmC8m"
    "k3fLvvtOV4f6bkHnD/O4eqALHRCrtgIuKSevC2Ns2F1NAVuXw9oFge5iEuhK0HiHwMt4kYr3vC1YNSRJFOIMsQw4L68BjQdPKuRp"
    "pwSKyS48d6yrQuPdAfWQq84AoqEq8tNqXboieIP2fYDDqyVwKrtc+tN5cAF3qkAz8Bfe/2aWOKWhRDGHVL+i8tME8in2lZ7FCfmF"
    "1DbhWstio+H7966viwAn9R2I8/OXCK0tFNTIGbt/jbPo9T2taVE8+Fvdw/AyoV204rnE6cfPrakFodw++OCaqn2HvsIHZvBuBnXa"
    "c2JDfcvEOm+opZ7VUiMnYYL5mmZrZf3K5Yx8kEWKbGd4Hg2vBoDuPd/zJroyNN4t+Vjc3kPZWkcqKV0nsnTLVGkmapuLqvFY1r/t"
    "FGPmTwOvpw0sVtM6TMi61AFEKO1Y3bEo954gIGGaIgi7QC1RXaUl8jAkQtC2ErzvDicA8JOe7r7Gif1nIPwNCMa/aoa/Gl65asNv"
    "qB2fGm8u+CQE23KBEpzGtVlgMANxCqVKv6lpqydUFBKhB4ZoqRxz99K7WuhzXqfxDsOMkzuSSYGExDKvPvF4lTG+wSmVu3LrFVeJ"
    "aickDYHKCr9qpxCX/gLM4wbDqa5jdE6a3nJSzZ4Uojzazx3UJG6147Rj+VGxZsN41Xm2DxSGHn2kpa4xHbnPAtpO4y0HdyUYX4Fr"
    "5FmJTDSr7XGeiBJaC1WyJ8oggVoOt0N/OlkG+jtQncabD/MUbz42gFQ0qtoasgqPkASeegM/X23ZWTBvuzcJggEYyfMvpiNdvu00"
    "PqPgosdQQ1ISSviOz+4AhBjiHNpijtOdoKLVYugKcd5gq6Z0i2L35fe3x5M8iwhfsVS+qawpXeVBiV9a6hUefMfBjwv3WrfK6DRf"
    "fKsHWtXeP+f49on5qARDLmCIxDF4TXU3PENxulMNEtCypR7he8HC1wYp60uAlGKj/4NUMd45vNJVovGiu0/XAhVhZ81ZXtMi1sAn"
    "8RDeWo5Ps/m73kB7iKrjNC3FQbreil2YvCBbl+D0MHjY0qpi4PanN8sLd6SLsaeNl9yDnKcqRUSY36I032xrhHjcm/g8xLZaiwt/"
    "2LuGXz33WleLxo8B9AmEF7YTaIU5p3WtcJUq0Kgo/+YhJ3X1XRahsMz7be6X96eL4rb0K+7TTtNBar93QdM0h9q7pmBgWzXvUozV"
    "JsqmlRUE/ia9IxkRrYWny5H+vsXp6Z+6f3RPAHOzqtdsE6jnVE/wofnR1mwBn7y8cX/SLShOG6+y3+Ptpy2Pmgbsv6CkUx3zfRlO"
    "5a6+8sjIHSSNDRWirZXF5QgsHQz8Z0zlnZ43rcmIsbLIg9yhpl1qXCSmRfnxcBpmBdT6dU1HzkeL/pW3vJiOL3Rl6DZd5pUcJdI8"
    "WqspydqtpAOEAv5Vxwi+Mh3cSX8eTH3tlG01nrL3HQ8BHPSZUfqEyqdbVGpDEAkVnSBltHh79XLog1OM3Ll2+rab7gYe1HkqCD27"
    "yFOxqt3nWX2VtINnRKbm5+clO8jaMWdVn9iwO9XjKzI6Z4qQKkvGELP2ZR4hLT3E53r+0B0tXe3Jj7PG6203Q+QDZOoNSdWkjZCf"
    "9YkQZ9/JmqlWhO8Yjdoqg0oRnvb09tnJFxszeCoDKCdBxSnWYomAu6rzGTXwUZ47aWmCcHtuX9sVOl/oXPHDSan7unZrSUkkOiqo"
    "FX6vJmv+uE/UUm+Yez0fPvg5Z3vOGq+z3SgqJunLfSAk2VNhKSJbNZRcc8CHlZk6ZSGW7Z0N9LRp6ezsSxywKl7xIVJCIGfHrLpZ"
    "1CmJVDWdOFGEW41MCcGpKs3V+yuKOaqWJusg8F3t1tNZ44X1uDhRT5Uz5OvkMy6BC7Bi9eODbLtlgkqC1kTtPLV1qGDoXeoK0fg2"
    "9k1C0/3JQ1r3qhValtRCElWw1Rfe3wmUgAVAT7JpaZ4IPG+0vAH76CrR+BT5fMsJjkQx1lQ97UKiNYmgiMjWovYlIaKYmKIZhK52"
    "tzmuh6PRcn7j6p5OP2v8dPocSrUwUZ2OFU2ppDXT4UUxt6/6ytxc7YWU5TUFVUQx7t9SQSZuoP32rrMvUGBD3CmLiRKfRN1bJcrR"
    "jjvyZNEBEkhezNqAg7T2dUXTnzx/4Lm6afv8uPmjuXiVgmfEeZq+rj+nXqaS8mRY8Zqu9Ikt7ceXHrVSi/MTXRFeUGGLH3PAT/jv"
    "Mea3og/XjtAPP6CARax9huroGqpjuKFOdQ11arihznQNdWa4oc51DXVuuKG6uobqGm4oS9dQluGGsnUNZRtuKEfXUI7Zhuoeaxqq"
    "e2y4oXTJvGs4mXd1ybxrOJl3dcm8aziZd3XJvGs4mXd1ybxrOJl3dcm8aziZd3XJvGs4mXd1ybxrOJl3dcm8aziZW7pkbhlO5pYu"
    "mVuGk7mlS+aW4WRu6ZK5ZTiZW7pkbhlO5pYumVuGk7mlS+aW4WRu6ZK5ZTiZW7pkbhlO5pYumVuGk7mtS+a24WRu65K5bTiZ27pk"
    "bhtO5rYumduGk7mtS+a24WRu65K5bTiZ27pkbhtO5rYumduGk7mtS+a24WRu65K5bTiZO7pk7hhO5o4umTuGk7mjS+aO4WTu6JK5"
    "YziZO7pk7hhO5o4umTuGk7mjS+aO4WTu6JK5YziZO7pk7hhO5o4umTuGk/nJ8bH2P4JsHpv/F1gcopQ="
)
ORIGINAL_GEN3_TM_ITEMS_SHA256 = "ab4bd0eb9677e29b5e7e1bc67e627525d40520b8198b51d8ed6b5a321c98e2df"

